[package]
name = "mpl-token-metadata"
version = "2.0.0"
description = "Metaplex Token Metadata SDK"
authors = ["Metaplex Developers <dev@metaplex.com>"]
repository = "https://github.com/metaplex-foundation/mpl-token-metadata"
license-file = "../../LICENSE"
edition = "2021"
readme = "README.md"

[lib]
crate-type = ["cdylib", "lib"]

[features]
test-sbf = []

[dependencies]
borsh = ">= 0.9"
num-derive = "^0.3"
num-traits = "^0.2"
solana-program = "^1.14"
thiserror = "^1.0"

[dev-dependencies]
assert_matches = "1.5.0"
solana-program-test = "^1.14"
solana-sdk = "^1.14"
spl-token = { version = ">= 3.5.0, < 5.0", features = ["no-entrypoint"] }
spl-associated-token-account = { version = ">= 1.1.3, < 3.0", features = ["no-entrypoint"] }
